[config]

[templates.fuzzel]
input_path = "~/.config/matugen/templates/fuzzel.ini"
output_path = "~/.config/fuzzel/colors.ini"

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/themes/matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/config'
post_hook = "pkill -USR1 cava"

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hypr.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.spicetify]
input_path = '~/.config/matugen/templates/spicetigy-colors.ini'
output_path = '~/.config/spicetify/Themes/text/color.ini'
post_hook = '(sleep 1; ~/.spicetify/spicetify refresh) &'

[templates.vesktop]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'
