[config]

[templates.fuzzel]
input_path = "~/.config/matugen/templates/fuzzel.ini"
output_path = "~/.config/fuzzel/colors.ini"

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/themes/matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.qt5]
input_path = '~/.config/matugen/templates/qt.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6]
input_path = '~/.config/matugen/templates/qt.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/config'
post_hook = "pkill -USR1 cava"

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hypr.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.color-scheme]
input_path = '~/.config/matugen/templates/color-scheme.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'
post_hook = 'plasma-apply-colorscheme BreezeDark && plasma-apply-colorscheme Matugen'

[templates.spicetify]
input_path = '~/.config/matugen/templates/spicetigy-colors.ini'
output_path = '~/.config/spicetify/Themes/text/color.ini'
post_hook = '(sleep 1; ~/.spicetify/spicetify refresh) &'

[templates.vesktop]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

[templates.zen]
input_path = '~/.config/matugen/templates/zen.css'
output_path = '~/.var/app/app.zen_browser.zen/.zen/1106fjd9/chrome/userChrome.css'
